language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t csareduardog29/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true csareduardog29/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-711055049092"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"