language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t csareduardog29/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true csareduardog29/docker-react npm test